app/Http/routes.php
<?php

    /*
    |--------------------------------------------------------------------------
    | Application Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register all of the routes for an application.
    | It's a breeze. Simply tell Laravel the URIs it should respond to
    | and give it the controller to call when that URI is requested.
    |
    */

    Route::get('/api/companies', 'ApiController@listCompanies');

    require_once('Routes/main_routes.php');
    require_once('Routes/client_routes.php');
    require_once('Routes/admin_routes.php');

    Route::get('/{post}', [
        'as'    => 'post.show',
        'uses'  => 'Main\PostController@show'
    ]);

    Route::get('/faq/computer-based-training', function(){ 
        return Redirect::to('/faq/online-training', 301); 
    });

    Route::get('/{category}/{post}', [
        'as'    => 'post.show',
        'uses'  => 'Main\PostController@showWithCategory'
    ]);

    Route::post('/onsite-and-customized-training',[
        'as'    => 'post.custom-training',
        'uses'  => 'Main\PostController@sendEmailCustom'
    ]);

    Route::get('/design', [
        'as'    => 'design',
        'uses'  => 'DesignController@index'
    ]);

app/Models/Order.php
<?php namespace App\Models;

use App\Observers\OrderObserver;
use App\Utilities\Constant;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{

    use SoftDeletes;

    /**
     * Table used by Model
     *
     * @var string
     */
    protected $table = 'orders';

    protected $dates = ['completed_at', 'deleted_at'];

    /**
     * Attributes that are mass assignable
     *
     * @var array
     */
    protected $fillable = ['user_id', 'user_csr_id', 'order_notes', 'status', 'paid_total',
                           'order_tax', 'order_fees_handling', 'total', 'completed_at', 'archived_at',
                           'shipping_address','shipping_zip','billing_address','billing_zip','shipping_rates',
                           'billing_company', 'shipping_company', 'billing_state', 'billing_city', 'shipping_state',
                            'shipping_city', 'shipping_county'];

    /**
     * @var bool
     */
    public $timestamps = true;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function items()
    {
        return $this->hasMany(OrderItem::class, 'order_id');
    }

    public function getValidItems()
    {

        if($this->items->count() == 0) return null;

        return $this->items->reject(function($val) {
            return ($val->orderable_type == Constant::REGISTRATION_ORDER
                and is_null($val->orderable()->withTrashed()->first()));
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function classDiscounts()
    {
        return $this->hasMany(ClassCombinationDiscount::class, 'order_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function classHalfPriceDiscounts()
    {
        return $this->hasMany(ClassHalfPriceDiscount::class, 'order_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function couponDiscounts()
    {
        return $this->hasMany(CouponDiscount::class, 'order_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function invoicePayments()
    {
        return $this->hasMany(InvoicedPayment::class, 'order_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function paymentTransactions()
    {
        return $this->hasMany(PaymentTransaction::class, 'order_id');
    }

    public function getTransaction()
    {
        $trans = null;
        try {

            if($this->status === Constant::INVOICED) {
                $trans = $this->invoicePayments()->firstOrFail();
            }

            if($this->status === Constant::COMPLETE) {
                $trans = $this->paymentTransactions()->firstOrFail();
            }

        } catch (\Exception $e) {
            return $trans;
        }

        return $trans;

    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function orderTransaction()
    {
        return $this->hasOne(OrderTransaction::class, 'order_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function orderAdjustments()
    {
        return $this->hasMany(OrderAdjustment::class, 'order_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function orderAdjustmentHistories()
    {
        return $this->hasMany(OrderAdjustmentHistory::class, 'order_id');
    }

    /**
     * Event in boot
     */
    public static function boot()
    {
        parent::boot();

        Order::observe(new OrderObserver());
    }

    public function csr()
    {
        return $this->belongsTo(User::class, 'user_csr_id');
    }

    public function scopeLast($query)
    {
        return $query->orderBy('id', 'DESC')->first();
    }

    public function isAvailable()
    {
        return $this->availability->gt(Carbon::now()->startOfDay());
    }

    public function getAvailabilityAttribute()
    {
        return $this->completed_at->addYear();
    }

    public function getCompletedAttribute()
    {
        return $this->completed_at->copy()
            ->setTimeFromTimeString($this->completed_at);
    }

    public function reminder()
    {
        return $this->morphMany(ReminderHistory::class, 'remindable');
    }

    public function scopeCompleted($query)
    {
        return $query->whereIn('orders.status', ['INVOICED', 'COMPLETE']);
    }

    public function getTotalCostAttribute()
    {
        return '$' . number_format($this->paid_total, 2, '.', ',');
    }

    public function getTotalInDollarsAttribute()
    {
        return '$' . number_format($this->total, 2, '.', ',');
    }

    public function notes()
    {
        return $this->hasMany(\App\Models\OrderNote::class, 'order_id');
    }

    public function getStatusFormattedAttribute()
    {
        if ($this->status == Constant::INVOICED) {
            return "<span class='label label-warning'>Invoiced</span>";
        } elseif ($this->status == Constant::COMPLETE) {
            return "<span class='label label-success'>Paid</span>";
        } elseif ($this->status == Constant::PENDING) {
            return "<span class='label label-danger'>Pending</span>";
        } else {
            return "<span class='label label-danger'>Pending</span>";
        }

    }

    public function scopeArchived($query)
    {
        return $query->whereNotNull('archived_at');
    }

    public function getIsArchivedAttribute()
    {
        return ($this->archived_at) ? 1 : 0;
    }

    public function archiveNow()
    {
        return $this->update([
            'archived_at' => Carbon::now()
        ]);
    }

    public function UnArchiveNow()
    {
        return $this->update([
            'archived_at' => NULL
        ]);
    }

    public function getIsCompletedAttribute()
    {
        return ($this->status == Constant::COMPLETE);
    }

    public function getBalanceAttribute()
    {

        $bal = $this->total - $this->paid_total;

        return ($bal >= 0) ? '$'.number_format($bal, 2, '.', ',') : '$0';
    }

    public function addToPaidTotal($amount)
    {
        $paid_total = (float) $amount + $this->paid_total;

        return $this->update(['paid_total' => $paid_total]);
    }

    public function isOnsite()
    {
        if($this->items()->count()) {
            return $this->items()->first()->orderable_type == Constant::ONSITE_TRAINING;
        }
        return false;

    }

    public function getCompleteBillingAddressAttribute()
    {

        return '<strong>'
            . $this->billing_company
            . '</strong>'
            . '<br/>'
            . $this->billing_address
            . '<br/>'
            . $this->billing_city.', '.$this->billing_state.' '.$this->billing_zip;
    }

    public function getCompleteShippingAddressAttribute()
    {

        $shipping = '<strong>'
            . $this->shipping_company
            . '</strong>'
            . '<br/>'
            . $this->shipping_address
            . '<br/>'
            . $this->shipping_city.', '.$this->shipping_state.' '.$this->shipping_zip;

        if(!empty(trim($this->shipping_county))) {
            $shipping .= ' (' . $this->shipping_county . ')';
        }

        return $shipping;
    }

    public function getCheckoutCombinationAttribute()
    {
        $product_count = 0;
        $course_count = 0;

        foreach ($this->items as $item) {
            if($item->orderable_type == 'ProductOrders') {
                $product_count++;
            } else {
                $course_count++;
            }
        }

        if($product_count and $course_count) {
            $type = 'PRODUCT_COURSE';
        } elseif($product_count) {
            $type = 'PRODUCT';
        } elseif($course_count) {
            $type = 'COURSE';
        }

        return $type;

    }

    public function getCurrentTotalAttribute()
    {
        return ($this->items()->count())
            ? $this->items->sum('price_charged')
            : 0;
    }

    public function getCurrentProductTotalAttribute()
    {
        return ($this->items()->count())
            ? $this->items()->productOrders()->get()->sum('price_charged')
            : 0;
    }

    public function getCurrentProductTotalTaxAttribute()
    {

        if(!$this->has_tax)
            return 0;

        if(empty($this->shipping_rates))
            return 0;

        if(empty($this->shipping_county))
            return 0;

        $current_prod_total = $this->current_product_total;

        $tax = StateTax::getTaxFromCountyName($this->shipping_county);

        $current_prod_total += $this->shipping_rates;

        return getPercentageAmountFromTotal($tax, $current_prod_total);

    }

    public function getCurrentTotal($state = '', $county = 1)
    {

        if($this->items()->count() == 0) return 0;

        $total = 0;

        foreach ($this->items as $item) {
            $total += $item->getTaxedPrice($state, $county);
        }

        return $total;
    }

    public function completedDateFormatted($format = 'l, F j, Y')
    {
        return $this->completed_at->format($format);
    }

    public function getPaymentMethodAttribute()
    {
        if ($this->status === Constant::INVOICED) {
            return 'Purchase Order';
        } else {
            return 'Credit Card';
        }
    }

    public function getHasMultipleClassesAttribute()
    {
        return ($this->items()->registrationOrders()->count() > 1) ? true : false;
    }

    public function getHasClassRegistrationAttribute()
    {

resources/views/admin/includes/_classes_modal.blade.php
<div class="modal fade" id="classesModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Hazardous Waste Management: The Complete Course (RCRA)</h4>
            </div>
            <div class="modal-body">
                <table class="table" id="classList">
                    <thead>
                    <tr>
                        <th>Date</th>
                        <th>City/State</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>Nov 1, 2017</td>
                            <td>Webcast</td>
                            <td><a href="#"
                                   data-type="CLASS"
                                   class="selectClass">Select</a></td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

resources/views/admin/includes/_classes_modal_content.blade.php
<table class="table" id="classList">
    <thead>
    <tr>
        <th>Date</th>
        <th>City/State</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>

    <tr>
        <td>Nov 1, 2017</td>
        <td>Seminar</td>
        <td><a href="#"
               data-type="CLASS"
               class="selectClass">Select</a></td>
    </tr>

    </tbody>
</table>

resources/views/admin/includes/class_modal.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="classModalLabel">Save Class</h4>
</div>

{!! Form::open(['method' => 'POST', 'url' => route('admin.class.add'), 'id' => 'classForm']) !!}
    {!! Form::hidden('location_id', 1) !!}
    <div class="modal-body">
        @if (isset($class))
            {!! Form::input('hidden', 'id', $class->id) !!}
        @endif

        {!! Form::input('hidden', 'course_id', $course->id) !!}
        {!! Form::input('hidden', 'course_type', $course->courseType->id) !!}

        {!! Form::rLabel('start_date', 'Start Date: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="form-group col-md-9 input-group">
            <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
            </div>
            {!! Form::input('text', 'start_date', isset($class) ? date('F d, Y', strtotime($class->start_date)) : '', [
                'class' => 'form-control',
                'id'    => 'startDate',
                'style' => 'display: inline;',
                'placeholder' => 'MM dd, yyyy',
                'required' => 'required',
            ]) !!}
        </div>

        {!! Form::rLabel('start_time', 'Start Time: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="bootstrap-timepicker form-group col-md-9 input-group">
            <div class="input-group-addon">
                <i class="fa fa-clock-o"></i>
            </div>
            {!! Form::input('text', 'start_time', isset($class) ? $class->start_time : '', [
                'class' => 'form-control',
                'id'    => 'startTime',
                'style' => 'display: inline;',
                'required' => 'required'
            ]) !!}
        </div>

        {!! Form::rLabel('end_date', 'End Date: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="form-group col-md-9 input-group">
            <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
            </div>
            {!! Form::input('text', 'end_date', isset($class) ? date('F d, Y', strtotime($class->end_date)) : '', [
                'class' => 'form-control',
                'id'    => 'endDate',
                'style' => 'display: inline;',
                'placeholder' => 'MM dd, yyyy',
                'required' => 'required'
            ]) !!}
        </div>

        {!! Form::rLabel('end_time', 'End Time: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="bootstrap-timepicker form-group col-md-9 input-group">
            <div class="input-group-addon">
                <i class="fa fa-clock-o"></i>
            </div>
            {!! Form::input('text', 'end_time', isset($class) ? $class->end_time : '', [
                'class' => 'form-control',
                'id'    => 'endTime',
                'style' => 'display: inline;',
                'required' => 'required'
            ]) !!}
        </div>

        {!! Form::label('instructor_name', 'Instructor: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="form-group col-md-9 input-group">
            <select name="instructor_id" class="form-control col-md-9 instructor">
                <option value="">-- Select Instructor --</option>
                @foreach ($instructors as $instructor)
                    <option value="{{ $instructor->id }}"
                            @if (isset($class) && $class->instructor && $class->instructor->id == $instructor->id) selected @endif>
                        {{ $instructor->name }}
                    </option>
                @endforeach
            </select>
        </div>

        @if ($isSeminar)

                {!! Form::label('location', 'Location: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="form-group col-md-9 input-group">
                    <select name="location_id" class="form-control col-md-9 location">
                        <option value="">-- Select Location --</option>
                        @foreach ($locations as $location)
                            <option value="{{ $location->id }}"
                                    @if (isset($class) && $class->location && $class->location->id == $location->id) selected @endif>
                                {{ $location->location }}
                            </option>
                        @endforeach
                    </select>
                </div>
            
        @endif

        {!! Form::label('website', 'Venue Info (link): ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="form-group col-md-9 input-group">
            {!! Form::input('text', 'website', isset($class) ? $class->website : '', [
                'class' => 'form-control',
            ]) !!}
        </div>

        {!! Form::label('instructions', 'Instructions: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="form-group col-md-9 input-group">
            {!! Form::textarea('instructions',  isset($class) ? $class->instructions : '', [
                'class' => 'form-control col-md-9',
                'style' => 'display: inline;'
            ]) !!}
        </div>

        <div style="text-align: right;">
            <button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary btn-flat">Save</button>
        </div>
    </div>

{!! Form::close() !!}

resources/views/admin/includes/error_message.blade.php
@if (Session::has('error_message'))
    <div class="box-container col-md-12">
        <div class="alert alert-danger alert-dismissible box box-success box-solid" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ Session::get('error_message') }}
        </div>
    </div>
@endif

resources/views/admin/includes/form_errors.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/includes/pager_details.blade.php
@if (isset($pager))
    <?php
    $start = ($pager->currentPage() - 1) * $pager->perPage() + 1;
    $total = $pager->total();

    if ($pager->currentPage() == $pager->lastPage()) {
        $end = $total;
    } else {
        $end = $start + $pager->perPage() - 1;
    }
    ?>

    <div class="pager-details">Result {{ $start }} - {{ $end }} of {{ $total }}</div>
@endif

resources/views/admin/includes/select_merge_customers.blade.php
<div class="modal-header panel-heading">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="classModalLabel">
        Which user should all the training history and address book entries be moved to?
    </h4>
</div>

{!! Form::open([
    'method' => 'POST',
    'url' => route('customers.merge.post'),
    'id' => 'merge-customers'
    ]) !!}
<div class="modal-body">

    <div class="alert alert-danger" style="display: none"></div>

    @foreach($customers as $customer)

        {!! Form::label('', '', [
            'class' => 'control-label']) !!}

        <div class="form-group col-md-12">
            {!! Form::radio('customer_id', $customer->id, '', [
            'class'    => 'customer_id',
            ]) !!}

            <input type="hidden" name="contacts[]" value="{{ $customer->id }}">

            <span>
                {{ $customer->first_name }} {{ $customer->last_name }}
            </span>
            <p>Email : {{ $customer->user ? $customer->user->email : 'No email.' }}</p>
        </div>
    @endforeach

    <div style="text-align: right;">
        <button type="button" class="btn btn-flat btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-flat btn-primary">Merge</button>
    </div>
</div>

{!! Form::close() !!}

resources/views/admin/includes/shipping_billing.blade.php
<hr/>
<div class="shipping_billing row">

            <div class="col col-xs-12 col-sm-6">
                <div class="billing_container">
                    <label><strong>Billing Address</strong></label>
                    <div class="panel panel-address panel-option panel-selected">
                        <div class="panel-body">
                            <a href="{{ route('admin.profile.edit', [ $user->contact->id ]) }}" class="edit" title="Edit" style="color: #333"><i class="fa fa-pencil pull-right" aria-hidden="true"></i></a>
                            <i class="fa fa-check-circle pull-left" aria-hidden="true" style="line-height: 3.6em; color:green;"></i>
                            {!! $user->contact->complete_billing_address  !!}
                            <input type="hidden" name="billing_company_default" value="{{ $user->contact->company }}" />
                            <input type="hidden" name="billing_address_default" value="{{ $user->contact->user_billing_address }}" />
                            <input type="hidden" name="billing_state_default" value="{{ $user->contact->user_billing_state }}" />
                            <input type="hidden" name="billing_city_default" value="{{ $user->contact->user_billing_city }}" />
                            <input type="hidden" name="billing_zip_default" value="{{ $user->contact->user_billing_zip }}" />
                        </div>
                    </div>
                    <div class="panel panel-option panel-form-button">
                        <div class="panel-body">
                            <strong><i class="fa fa-plus-circle" aria-hidden="true"></i> Use another address</strong>
                        </div>
                    </div>
                    <div class="panel panel-form-address" style="display: none">
                        <input type="hidden" name="billing_custom" class="custom_flag" value="0"/>
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="billing_company">Company/Name:</label>
                                <input name="billing_company" type="text" class="form-control" id="billing_company">
                            </div>
                            <div class="form-group">
                                <label for="billing_address1">Address:</label>
                                <input name="billing_address1" type="text" class="form-control" id="billing_address1">
                            </div>
                            <div class="form-group">
                                <label for="billing_city">City:</label>
                                <input name="billing_city" type="text" class="form-control" id="billing_city">
                            </div>
                            <div class="form-group">
                                <label for="billing_state">State:</label>
                                {!! Form::select('billing_state', $states, '', [
                                        'class' => 'form-control'
                                    ]) !!}
                            </div>
                            <div class="form-group">
                                <label for="billing_zip">Zip:</label>
                                <input name="billing_zip" type="number" class="form-control" id="billing_zip" maxlength="5" size="5" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col col-xs-12 col-sm-6">
                <div class="shipment_container">
                    <label><strong>Shipping Address</strong></label>
                    <div class="panel panel-address panel-option panel-selected">
                        <div class="panel-body">
                            <input type="hidden" name="po_shipping_zip" value="{{ $user->contact->zip }}"/>
                            <input type="hidden" name="po_shipping_state" value="{{ $user->contact->user_shipping_state }}"/>
                            <input type="hidden" name="tax_rate" value="0"/>
                            <input type="hidden" name="shipping_rates" value=""/>
                            <a href="{{ route('admin.profile.edit', [ $user->contact->id ]) }}" class="edit" title="Edit" style="color: #333"><i class="fa fa-pencil pull-right" aria-hidden="true"></i></a>
                            <i class="fa fa-check-circle pull-left" aria-hidden="true" style="line-height: 3.6em; color:green;"></i>
                            {!! $user->contact->complete_shipping_address  !!}
                            <div style="display: block; margin-top: 5px; display: none">
                                {!! Form::select('shipment_county_default', $counties, '', [
                                    'class' => 'form-control',
                                ]) !!}
                            </div>
                            <input type="hidden" name="shipment_company_default" value="{{ $user->contact->company }}" />
                            <input type="hidden" name="shipment_address_default" value="{{ $user->contact->user_shipping_address }}" />
                            <input type="hidden" name="shipment_state_default" value="{{ $user->contact->user_shipping_state }}" />
                            <input type="hidden" name="shipment_city_default" value="{{ $user->contact->user_shipping_city }}" />
                            <input type="hidden" name="shipment_zip_default" value="{{ $user->contact->user_shipping_zip }}" />
                        </div>
                    </div>
                    <div class="panel panel-option panel-form-button">
                        <div class="panel-body">
                            <strong><i class="fa fa-plus-circle" aria-hidden="true"></i> Use another address</strong>
                        </div>
                    </div>
                    <div class="panel panel-form-address" style="display: none">
                        <input type="hidden" name="shipping_custom" class="custom_flag" value="0"/>
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="shipment_company">Company/Name:</label>
                                <input name="shipment_company" type="text" class="form-control" id="shipment_company">
                            </div>
                            <div class="form-group">
                                <label for="shipment_address1">Address:</label>
                                <input name="shipment_address1" type="text" class="form-control" id="shipment_address1">
                            </div>
                            <div class="form-group">
                                <label for="shipment_city">City:</label>
                                <input name="shipment_city" type="text" class="form-control" id="shipment_city">
                            </div>
                            <div class="form-group">
                                <label for="shipment_state">State:</label>
                                {!! Form::select('shipment_state', $states, '', [
                                    'class' => 'form-control'
                                ]) !!}
                            </div>
                            <div class="form-group" style="display: none">
                                <label for="shipment_county">County:</label>
                                {!! Form::select('shipment_county', $counties, '', [
                                    'class' => 'form-control',
                                ]) !!}
                            </div>
                            <div class="form-group">
                                <label for="shipment_zip">Zip:</label>
                                <input name="shipment_zip" type="number" class="form-control" id="shipment_zip" maxlength="5" size="5" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

<style>
    .shipping_billing .panel {
        border: none;
        -webkit-box-shadow: none;
        box-shadow: none;
    }
    .shipping_billing .panel-address .panel-body {
        line-height: 1.2em;
    }
    .shipping_billing .panel:hover {
        background: #f8f8f8;
    }
    .shipping_billing .panel-option {
        cursor: pointer;
        border: none;
    }
    .shipping_billing .panel-selected {
        border: 1px solid #9ca643 !important;
        box-shadow: 0 2px 4px 0 rgba(0,0,0,.09);
    }
</style>

resources/views/admin/includes/success_message.blade.php
@if (Session::has('success_message'))
    <div class="box-container col-md-12">
        <div class="alert alert-success alert-dismissible box box-success box-solid" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ Session::get('success_message') }}
        </div>
    </div>
@endif